name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: ./
        with: 
          working-directory: vue_webapp/cypress/integration
          build: npx cypress info
      
